### ISSUE TITLE
It seems that the hap1 of gp032 and gp034 are missing

### ISSUE THREAD

**Issue by WeiYang-BAI** [muddinmbru/arab_pangenome_reference#2]
Hi, it seems that the hap1 of gp032 and gp034 are missing on https://www.mbru.ac.ae/the-arab-pangenome-reference/

Best regards,
Weiyang Bai

**Comment by muddinmbru** [comment]
Dear Weiyang Bai,
Thanks for reaching out. We have done some additional resequencing, and we will replace the current data by the end of this week. We will reupload to our website and update you with the gender info as well.

Regards,
Mohammed



________________________________
From: WeiYang-BAI ***@***.***>
Sent: Monday, May 6, 2024 6:12 AM
To: muddinmbru/arab_pangenome_reference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [muddinmbru/arab_pangenome_reference] It seems that the hap1 of gp032 and gp034 are missing (Issue #2)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

This message is from an external sender. Please take care when responding, clicking links or opening attachments.


Hi, it seems that the hap1 of gp032 and gp034 are missing on https://www.mbru.ac.ae/the-arab-pangenome-reference/. Additionally, is it possible to obtain the gender information of all the samples?"

Best regards,
Weiyang Bai

**Comment by WeiYang-BAI** [comment]
Hi Mohammed,

Thanks for the prompt reply! I will wait for the latest data. Also, just to clarify, is the "gp001" in the filename equal to "APR001" (and for 002, 003... etc) in the preprints?

Best regards,
Weiyang

**Comment by muddinmbru** [comment]
Yes, we will clarify the names as well. Sorry for the confusion.

________________________________

**Comment by yeeus** [comment]
> Dear Weiyang Bai,
> Thanks for reaching out. We have done some additional resequencing, and we will replace the current data by the end of this week. We will reupload to our website and update you with the gender info as well.
> 
> Regards,
> Mohammed
> […](#)

Hi @muddinmbru @WeiYang-BAI, where could I get the gender info about APR assemblies?
Best wishes.
